# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{buffpojken-gdata4ruby}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["buffpojken"]
  s.date = %q{2011-12-02}
  s.email = ["daniel@sykewarrior.com"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "CHANGELOG",
    "lib/gdata4ruby.rb",
    "lib/gdata4ruby/acl/access_rule.rb",
    "lib/gdata4ruby/base.rb",
    "lib/gdata4ruby/gdata_object.rb",
    "lib/gdata4ruby/oauth_service.rb",
    "lib/gdata4ruby/request.rb",
    "lib/gdata4ruby/service.rb",
    "lib/gdata4ruby/utils/utils.rb"
  ]
  s.homepage = %q{https://github.com/buffpojken/GData4Ruby}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A full featured wrapper for interacting with the base Google Data API}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oauth>, [">= 0.4.4"])
    else
      s.add_dependency(%q<oauth>, [">= 0.4.4"])
    end
  else
    s.add_dependency(%q<oauth>, [">= 0.4.4"])
  end
end

